name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tkinter
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install NASM
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm
    
    - name: Test Python syntax
      run: |
        python -m py_compile src/python/*.py
    
    - name: Test Assembly compilation
      run: |
        cd src/assembly
        nasm -f elf64 dma_controller.asm -o dma_controller.o
        nasm -f elf64 bus_arbitration.asm -o bus_arbitration.o
        nasm -f elf64 memory_manager.asm -o memory_manager.o
    
    - name: Run Python tests
      run: |
        cd src/python
        python -c "import gui_dma_tester; print('GUI module imported successfully')"
        python -c "import dma_simulator; print('DMA simulator module imported successfully')"
        python -c "import bus_controller; print('Bus controller module imported successfully')"
    
    - name: Build Docker image
      run: |
        chmod +x scripts/docker-build.sh
        ./scripts/docker-build.sh
    
    - name: Test Docker container
      run: |
        docker run --rm simulador-dma:latest python -c "print('Docker container test successful')"
    
    - name: Run Makefile tests
      run: |
        make clean
        make all
        make test
    
    - name: Check project structure
      run: |
        echo "Checking project structure..."
        ls -la
        ls -la src/
        ls -la src/assembly/
        ls -la src/python/
        ls -la scripts/
        echo "Project structure validation complete"